[tool.poetry]
name = "profiling-stuff"
version = "0.1.0"
description = ""
authors = ["Kausthub Krishnamurthy <kausthub.k@live.com>"]
readme = "README.md"
packages = [{include = "profiling_stuff"}]

[tool.poetry.dependencies]
python = "^3.10"
py-spy = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
